In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# This week we review the last several weeks.

# We have introduced many ideas: variables, assignment, evaluation.  We can directly type commands and evaluate
# them.  For exmple simple arithmetic: 


1+1 

2

In [3]:
# We normally create variable by assignment using the = operator
# Expressions like:

a = 'hello'
f = np.log10(100)
g =2^10 - 1
h =['1','why',2,'because','!']
# Variables can have different types.  What others have we seen besides numerical and string?

# Are f & g the same type?  How can you find out?

#What about h?  What type is it?

#How do you get the individual items in h?


In [6]:
# We introduced numpy arrays.  Arrays are very important data structures and used to represent most data.  
# Although they can have lots of dimensions it is convenient to think of

# 1d array -> time course of a signal
# 2d array -> an image
# 3d array -> a volume, ie stack of images

# The command for generating a array consisting of an ordered list of 
# integers with a start and an end and given increment (or decrement) is
# used a lot.  Write a command to store the sequence  1 3 5 7 9
# and store the result in variable called a



[1 3 5 7 9]


In [16]:
#Arrays can be created in many ways.  We can type them in directly.  For example:

a=np.array([ [1, 2, 3], [4, 5, 6] , [7, 8, 9] ])
print(a)

# makes a 2d matrix with 3 rows and 3 columns.

# Numpy has many built in functions for creating arrays.

# for example use numpy commands zeros and ones to create a 3x4 array full of zeros and a 4x3 array full of ones.
#Store the results in variables called a & b



#Bonus: numpy performs arithmetic element by element on arrays.  Write a command to add the transpose of a to b



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [4]:
# 4.  Write a command to create a 1x10 matrix filled with normally distributed random numbers.  
#Assign the result to b.

# hint: check out numpy random command randn



In [6]:
# There are many numpy  functions which report different properties of the array.  Very useful.

# size gives the total number of elements of the array
# shape gives the number of rows and columns 
# mean gives the mean value of the numbers stored in the array
# std gives the standard deviation of the numbers stored in the array
# sum adds the numbers in the array
# amin finds the smallest value, argmin the index
# amax finds the largest value, argmax the index

# Write commands and evaluate to calculate each of the above quantities for
# your random matrix, b.

# Bonus:  Find both the largest and smallest values and their corresponding positions in the
# array (index).




In [8]:
# Indexing (or slicing as Software Carpentry calls it) allows us to specify which part of
# the array we want to isolate by referring to those elements in
# square brackets [] after the variable name.  For example, to see the value in
# the first row and first column of b we would evaluate:
# Use this for b:

b=np.random.randn(4,4);

b[0,0]

# Write a command to add the elements of b which are on the diagonal of the
# matrix.  Hint:  The diagonal refers to the elements for which the row and
# column numeber are equal.  b[0,0] is the first element on the diagonal of
# b.



1.2910306498782076

In [19]:
# 6. Apply basic indexing to isolate the first 3 rows and
# first 3 columns of your matrix b.  Assign the result to a new variable
# called c.



# 7. Overwrite variable c.  This time store the last 3 rows and columns of b.



[[ 0.34124379  0.0967945  -0.77234963  1.37936597  0.87152401 -0.42373614
  -0.4773316  -0.54545504 -1.01333988 -0.24282962]]
[]
[]


In [9]:
# 8.  We also introduced logical indexing.  This indexing method allows us
# to isolate those elements of a matrix which satisfy a certain condition.
# An intensity threhold applied to an image is an example.  It gives you
# all the pixels which are above the threhold.

# Let's try exactly this application.

# matplotlib has a command called imread.
# Use imread to read in the data in the file cell1.tif, assign the result
# to a variable named dat.


#Use matplotlib imshow to display the image


# logically index dat to find those pixels which are greater than 200.
# Assign the rsult to a variable called th.

# Use matplotlib imshow to display the image 



In [11]:
#We spent some time on strings in the context of filenames.

#store 'cell1.tif' in a string variable called myfile.  Use matplotlib imread to read it in and store it in a 
#variable called c1 and then imshow to display.



In [12]:
# Use the + operator in strings concantenates (joins) them.  So we can make new file names by joining bits of strings
# together. For example:

myfile='cell'+str(1)+'.tif'
print(myfile)

# recall the str function which converts the number 1 to the
# string '1' for us.

# This lends itself to the quick generation of filenames using loops
# which can be a easy way to read in your data.

# 9. Write a loop to automatically generate the filenames of cell1.tif
# through cell3.tif.



# Bonus: read each image in and store in 1 plane of a 3d matrix.  where
# the dimensions represent x y pixels and cell number.  Call your matrix
# cells and initalize it to all elements equal to zero when you create it.
# (with zeros).  Use shape to find the size of the image and to help you
# when creating the array cells.


    



cell1.tif


In [14]:
# 10.  Add commands to your loop to display the image as it is read in.  Title
# each figure with the filename.


